services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/0_init.sql
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: zipecodedb
      MYSQL_USER: admin
      MYSQL_PASSWORD: superadmin
      MYSQL_ROOT_PASSWORD: superadmin
      SERVICES_TAGAS: dev
      SERVICES_NAME: mysqldb
    networks:
      - internalnet
networks:
  internalnet:
    driver: bridge
    
    

