CREATE DATABASE IF NOT EXISTS zipecodedb;
CREATE TABLE IF NOT EXISTS zipecodedb.zipecodes (
	id INT NOT NULL AUTO_INCREMENT,
    cep VARCHAR(9) DEFAULT NULL,
    logradouro VARCHAR(100) DEFAULT NULL,
    bairro VARCHAR(100) DEFAULT NULL,
    localidade VARCHAR(100) DEFAULT NULL,
    uf VARCHAR(100) DEFAULT NULL,
    complemento VARCHAR(100) DEFAULT NULL,
    ibge VARCHAR(100) DEFAULT NULL,
    gia VARCHAR(100) DEFAULT NULL,
    ddd VARCHAR(100) DEFAULT NULL,
    siafi VARCHAR(100) DEFAULT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
)
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4
COLLATE=utf8mb4_0900_ai_ci;
